version: "3"

services:
  fooo:
    security_opt:
      - apparmor=static_profile

    build: .
    cap_add:
      - CHOWN

    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN

    ports:
      - "2048:2048"

