version: "3"

services:
  mounty:
    security_opt:
       - "apparmor:simple_mount"
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
       - "/home/ubuntu/SecureWilly/volumes/data:/data_here"

