version: "2.3"

services:
  mounty:
    security_opt:
       - "apparmor:simple_mount"
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
       - "/home/ubuntu/Security-on-Docker/Docker_tests/mount/simple_mount/data:/mount_here"

