version: "3"

services:
  foo:
    build:
      context: .
      dockerfile: Dockerfile

    cgroup_parent: m-executor-abcd

      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M

    security_opt:
      - apparmor=static_profile

    ulimits:
      # Single number or mapping with soft + hard limits
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

