version: "3"

services:
  ulim_ti:
    build:
      context: .
      dockerfile: Dockerfile

  # These options have to be activated if I want to enter interactive mode in the container
    stdin_open: true
    tty: true

    security_opt:
     - "apparmor:ulimit_ti_profile"

    ulimits: # Single number or mapping with soft + hard limit
      nproc:
       soft: 1024
       hard: 1024
