version: "3"

services:
  mounty:
    security_opt:
       - "apparmor:static_profile"
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
       - "/home/ubuntu/Security-on-Docker/test_genprof/mount/mount_rule_missing/data:/mount_here"

