version: '3'
services:
  web:
    security_opt:
     - apparmor=static_profile
    build: .
    ports:
     - "5000:5000"
    volumes:
     - "/home/fanilicious/Diplomatiki/composet:/mounty"
  redis:
    image: "redis:alpine"
