version: '3'
services:
  attack:
    security_opt:
     - "apparmor:attacker_profile"
    build: .
    cap_add:
     - SYS_ADMIN
     - SYS_PTRACE
    pid: "host"
#    ports:
#    - "5000:5000"
#   volumes:
#    - "/home/ubuntu/Security-on-Docker/Docker_tests/ports_example_no2:/mountdir"
  dind:
    privileged: true
    image: "docker:dind"
