version: "3"

services:
  mounty:
    security_opt:
      - apparmor:static_profile
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - "/home/fanilicious/Diplomatiki/mount/data:/mount_here"
