version: "3"

services:
  ulim:
    build:
      context: .
      dockerfile: Dockerfile

    security_opt:
      - apparmor:unconfined

    ulimits:
      # Single number or mapping with soft + hard limits
      nproc: 1
      nofile:
        soft: 20000
        hard: 40000

