version: "3"

services:
  devi:
    build:
      context: .
      dockerfile: Dockerfile

    privileged: true
    cap_add:
      - SYS_ADMIN

    devices:
      - "/dev/tmp0:/dev/tty0"

#    security_opt:
 #     - apparmor=static_profile
    tty: true
