version: "3"

services:
  ulim:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ulimits:
      # Single number or mapping with soft + hard limits
      nproc: 
        soft: 1
        hard: 2
      nofile:
        soft: 20000
        hard: 40000

