version: "3"

services:

  db:
    container_name: matterdb
    image: matterdb
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - /home/fanilicious/Projects/SecureWilly/MatterMost/volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost

  app:
    container_name: matterapp
    image: matterapp
    build: 
      context: app
      args:
        - edition=team
        - PUID=1000
        - PGID=1000
    restart: unless-stopped
    volumes:
      - /home/fanilicious/Projects/SecureWilly/MatterMost/volumes/app/mattermost/config:/mattermost/config:rw
      - /home/fanilicious/Projects/SecureWilly/MatterMost/volumes/app/mattermost/data:/mattermost/data:rw
      - /home/fanilicious/Projects/SecureWilly/MatterMost/volumes/app/mattermost/logs:/mattermost/logs:rw
      - /home/fanilicious/Projects/SecureWilly/MatterMost/volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - /home/fanilicious/Projects/SecureWilly/MatterMost/volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10

  web:
    container_name: matterweb
    image: matterweb
    build: web
    ports:
      - "80:80"
      - "443:443"
    read_only: true
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
