FROM ubuntu:latest
MAINTAINER Fani Dimou <fani.dimou92@gmail.com>

COPY for_container.sh .

#Create userA with password A
#RUN useradd -m userA && echo "userA:A" | chpasswd
#USER userA
ENTRYPOINT /bin/bash
